### ISSUE TITLE
Change voice and accent of tts

### ISSUE THREAD

**Issue by Akashic101** [LordTocs/CastMate#164]
I noticed that during the [youtube-tutorial ](https://youtu.be/3I_Kg5fgVxA?t=523) the voice is a male one with an English accent. However when I do the same on my local PC the voice is a female one with a German accent. An option to change which voice and accent should be used would be very nice, since a German voice speaking English sounds a little bit weird.

On that note, how does CastMaste know which language and accent to use by default? Is this orientated by the system-language of the user? Would switching my system-language to English fix this issue?

**Comment by Akashic101** [comment]
Here is a recording what it sounds like on my PC to better illustrate the issue: https://youtu.be/tZgxp-UYabk

**Comment by LordTocs** [comment]
Hmm. I had thought CastMate used the default voice picked in the windows Speech settings.

However, after some investigation it seems just to ignore it. I've added a drop down to select the voice to use per action. So the next release will help you out. You can install other language packs to get voices with different accents. In the video I use Microsoft David.
