### ISSUE TITLE
Twitch Chat Commands Need to Require a Command

### ISSUE THREAD

**Issue by erin-fitzpatric** [LordTocs/CastMate#167]
If you create a Twitch chat command but do not set a command (likely by mistake), the chat command will fire with every chat. A command should be a requirement to save OR it should provide a warning that this behavior will happen.

![image](https://user-images.githubusercontent.com/46466305/186568106-5342293d-6dec-4457-bc5c-805a3e178410.png)

**Comment by LordTocs** [comment]
Commands have been overhauled in 0.5
