### ISSUE TITLE
Optional Bits usage?

### ISSUE THREAD

**Issue by Catreina** [LordTocs/CastMate#89]
Is it possible to add bit integration with this? So someone could optionally use bits for some of the interactions?  I ask because I noticed that Twitch Polls has the option to use bits or channel points to "skew the voting" now.

**Comment by LordTocs** [comment]
I really like the idea of having some commands with a bits price. Right now you can have actions run based on how many bits  are cheered. 

As an easy way to introduce this feature we could add a new trigger for chat commands that come with bits. They'd have to cheer with bits and supply a chat command in the cheer. This doesn't sound particularly user friendly though, especially in the case of a typo or something. But it would be easy to implement.

To do it right we'd probably have to make a bits-enabled twitch extension. One with buttons you configure with the bit prices and descriptions. Then have the extension contact CastMate when someone redeems one with bits. Essentially building a channel points reward system but for bits.

I will look into what it will take for an extension to do this.

**Comment by LordTocs** [comment]
It took a while, but this is finally a thing and I can close this issue.

CastMate's companion twitch extension SpellCast is out and lets you set up bit based triggers.

https://www.spellcast.gg/
